openapi: '3.0.2'
info:
  title: Movies Api
  version: '1.0'
servers:
  - url: https://api.server.test/v1

components:
  schemas:
    movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        imageUrl:
          type: string
        description:
          type: string
    movies:
      type: object
      properties:
        movies:
          type: array
          items:
            $ref: '#/components/schemas/movie'
        count:
          type: integer
        message:
          type: string
          description: explanation of response.

paths:
  /movies:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movies'
          